#!/bin/bash

system=$(uname -s)
case $system in
  Linux*)    
    find . -type f -name "*.go" -exec sed -i 's/github.com\/concourse\/concourse/github.com\/chenbh\/concourse\/v6/g' {} +;;
  Darwin*)    
    find . -type f -name "*.go" -exec sed -i '' 's/github.com\/concourse\/concourse/github.com\/chenbh\/concourse\/v6/g' {} +;;
esac
