package accessor

import (
	"github.com/concourse/concourse/atc/types"
)

const (
	MemberRole   = "member"
	OwnerRole    = "owner"
	OperatorRole = "pipeline-operator"
	ViewerRole   = "viewer"
)

var DefaultRoles = map[string]string{
	types.SaveConfig:                    MemberRole,
	types.GetConfig:                     ViewerRole,
	types.GetCC:                         ViewerRole,
	types.GetBuild:                      ViewerRole,
	types.GetCheck:                      ViewerRole,
	types.GetBuildPlan:                  ViewerRole,
	types.CreateBuild:                   MemberRole,
	types.ListBuilds:                    ViewerRole,
	types.BuildEvents:                   ViewerRole,
	types.BuildResources:                ViewerRole,
	types.AbortBuild:                    OperatorRole,
	types.GetBuildPreparation:           ViewerRole,
	types.GetJob:                        ViewerRole,
	types.CreateJobBuild:                OperatorRole,
	types.RerunJobBuild:                 OperatorRole,
	types.ListAllJobs:                   ViewerRole,
	types.ListJobs:                      ViewerRole,
	types.ListJobBuilds:                 ViewerRole,
	types.ListJobInputs:                 ViewerRole,
	types.GetJobBuild:                   ViewerRole,
	types.PauseJob:                      OperatorRole,
	types.UnpauseJob:                    OperatorRole,
	types.ScheduleJob:                   OperatorRole,
	types.GetVersionsDB:                 ViewerRole,
	types.JobBadge:                      ViewerRole,
	types.MainJobBadge:                  ViewerRole,
	types.ClearTaskCache:                OperatorRole,
	types.ListAllResources:              ViewerRole,
	types.ListResources:                 ViewerRole,
	types.ListResourceTypes:             ViewerRole,
	types.GetResource:                   ViewerRole,
	types.UnpinResource:                 OperatorRole,
	types.SetPinCommentOnResource:       OperatorRole,
	types.CheckResource:                 OperatorRole,
	types.CheckResourceWebHook:          OperatorRole,
	types.CheckResourceType:             OperatorRole,
	types.ListResourceVersions:          ViewerRole,
	types.GetResourceVersion:            ViewerRole,
	types.EnableResourceVersion:         OperatorRole,
	types.DisableResourceVersion:        OperatorRole,
	types.PinResourceVersion:            OperatorRole,
	types.ListBuildsWithVersionAsInput:  ViewerRole,
	types.ListBuildsWithVersionAsOutput: ViewerRole,
	types.GetResourceCausality:          ViewerRole,
	types.ListAllPipelines:              ViewerRole,
	types.ListPipelines:                 ViewerRole,
	types.GetPipeline:                   ViewerRole,
	types.DeletePipeline:                MemberRole,
	types.OrderPipelines:                MemberRole,
	types.PausePipeline:                 OperatorRole,
	types.ArchivePipeline:               OwnerRole,
	types.UnpausePipeline:               OperatorRole,
	types.ExposePipeline:                MemberRole,
	types.HidePipeline:                  MemberRole,
	types.RenamePipeline:                MemberRole,
	types.ListPipelineBuilds:            ViewerRole,
	types.CreatePipelineBuild:           MemberRole,
	types.PipelineBadge:                 ViewerRole,
	types.RegisterWorker:                MemberRole,
	types.LandWorker:                    MemberRole,
	types.RetireWorker:                  MemberRole,
	types.PruneWorker:                   MemberRole,
	types.HeartbeatWorker:               MemberRole,
	types.ListWorkers:                   ViewerRole,
	types.DeleteWorker:                  MemberRole,
	types.SetLogLevel:                   MemberRole,
	types.GetLogLevel:                   ViewerRole,
	types.DownloadCLI:                   ViewerRole,
	types.GetInfo:                       ViewerRole,
	types.GetInfoCreds:                  ViewerRole,
	types.ListContainers:                ViewerRole,
	types.GetContainer:                  ViewerRole,
	types.HijackContainer:               MemberRole,
	types.ListDestroyingContainers:      ViewerRole,
	types.ReportWorkerContainers:        MemberRole,
	types.ListVolumes:                   ViewerRole,
	types.ListDestroyingVolumes:         ViewerRole,
	types.ReportWorkerVolumes:           MemberRole,
	types.ListTeams:                     ViewerRole,
	types.GetTeam:                       ViewerRole,
	types.SetTeam:                       OwnerRole,
	types.RenameTeam:                    OwnerRole,
	types.DestroyTeam:                   OwnerRole,
	types.ListTeamBuilds:                ViewerRole,
	types.CreateArtifact:                MemberRole,
	types.GetArtifact:                   MemberRole,
	types.ListBuildArtifacts:            ViewerRole,
	types.GetWall:                       ViewerRole,
}
